kind: ServiceAccount
apiVersion: v1
metadata:
  name: warm-images-svc-acc
  namespace: warm-images
automountServiceAccountToken: true
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: warm-images-clusterrole-binding
  namespace: warm-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: warm-images-svc-acc
    namespace: warm-images