apiVersion: v1
kind: ConfigMap
metadata:
  name: wi-namespaces-cm
data:
  list.spaces: "ingress-nginx monitoring network-buddy warm-images"
  # TODO: add a global namespace option?
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wi-controller
  namespace: warm-images
  labels:
    app: wi-controller
  annotations:
    app: wi-controller
spec:
  selector:
    matchLabels:
      app: wi-controller
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wi-controller
      annotations:
        app: wi-controller
    spec:
      serviceAccountName: warm-images-svc-acc
      terminationGracePeriodSeconds: 1
      containers:
        - name: wi-controller
          image: reg.captainjustin.space/wi-controller:local
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /namespaces
              name: wi-namespaces-cm
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP
              value: CONTROLLER
            - name: LISTEN_ADDR
              value: :8080
            - name: NATS_ADDR
              value: nats://wi-nats-client:4222
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 3
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 3
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 5m
              memory: 32Mi
            limits:
              cpu: 20m
              memory: 32Mi
      volumes:
        - name: wi-namespaces-cm
          configMap:
            name: wi-namespaces-cm
  revisionHistoryLimit: 1
