apiVersion: v1
kind: ConfigMap
metadata:
  name: wi-namespaces-cm
data:
  list.spaces: "*"
  nats.username: "nats_client"
  nats.password: "sY6GYz5c9W"
  # list.spaces: "ingress-nginx monitoring network-buddy warm-images"
  # "nats_client", "sY6GYz5c9W"))
  # TODO: add a global namespace option?
