apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "warm-images.configmap" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  list.spaces: {{ .Values.list | quote }}
  ignore.spaces: {{ .Values.ignore | quote }}
  nats.username: {{ .Values.nats.username | quote }}
  nats.password: {{ .Values.nats.password | quote }}
