apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "warm-images.controllerName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "warm-images.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "warm-images.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "warm-images.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "warm-images.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "warm-images.customRegistry" . }}{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP
              value: CONTROLLER
            - name: LISTEN_ADDR
              value: :8080
            - name: NATS_ADDR
              value: {{ .Values.nats.url }}
            - name: HOST_IP
              value: "Controller"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /config
              name: {{ include "warm-images.configmap" . }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ include "warm-images.configmap" . }}
          configMap:
            name: {{ include "warm-images.configmap" . }}
  revisionHistoryLimit: 1