apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "warm-images.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "warm-images.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "warm-images.clusterRoleBindingName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "warm-images.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}